name: Update Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash update_snake.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update snake animation"
